apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
spec:
  containers:
    - name: envar-demo-container
      image: nginx
      env:
      - name: COURSE
        valueFrom:
          configMapKeyRef:
            key: COURSE
      - name: PERSON
        valueFrom:
          configMapKeyRef:
            key: TRAINER
      - name: DURATION
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: DURATION
          