apiVersion: v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: # these lables are replica set lables, every k8 resources can have labels.
    app: guestbook
    tier: frontend
spec:
  # Modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # these lables should match with pod labels
      tier: frontend
      app: nginx
      environment: dev
  template: # this one is nothing but pod defination
    metadata:
      labels: # these are the pod lables
        tier: frontend
        app: nginx
        environment: dev
    spec:
      containers:
        - name: nginx
          image: nginx
    