- name: testing variable precedence
  hosts: localhost
  # vars:
  #   NAME: Raj-play
  # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: please enter Trainer name
  #   private: false
  tasks:
  - name: variable at task level
#    vars: 
#      NAME: Raj-task
    ansible.builtin.debug:
      msg: "Trainer name is: {{NAME}}"


# First preference from command line
# Second preference is task level
# Third preference is vars_files
# fourth preference is from prompt
# fifth preference is from play level
# sixth is inventory 
# seventh is Roles