- name: simple conditions
  hosts: localhost
  vars:
    NAME: Devops
  tasks: 
    - name: run this if name is Devops
      ansible.builtin.debug:
        msg: "Hello {{NAME}}"
      when: NAME == "Devops"
# - name: check directory exist
#   hosts: localhost
#     tasks:
#     - name: check if test directory exist
#       ansible.builtin.stat:
