- name: install packages
  hosts: mangodb
  become: yes
  tasks:
    - name: install package
      ansible.builtin.yum:
        name: "{{item}}"
        state: installed
      loop:
        - nginx
        - postfix
