- name: install packages
  hosts: mangodb
  become: yes
  tasks:
    - name: install package
      ansible.builtin.yum:
        name: "{{item}}"
        state: installed
      # lit of map
      loop:
        - {name: 'nginx', state: 'absent'}
        - {name: 'postfix', state: 'installed'}
        - {name: 'cyrus-sasl-plain', state: 'absent'}
        - {name: 'mailx', state: 'installed'}
        