- name: Install MYSQL component
  hosts: mysql 
  become: yes
  tasks:
    - name: Disable MYSQL current version
      ansible.builtin.command:  yum module disable mysql -y

    - name: copy mysql repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Install MySQL community server
      ansible.builtin.yum:  
        state: installed 
    
    - name: restart catalogue
      ansible.builtin.service:  
        name: mysqld
        state: started  
        enabled: true
    
    - name: setup mysql root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

