- name: Install RabbitMQ
  hosts: rabbitmq 
  become: yes
  tasks: 
    - name: configure rabbitmq yum repo
      ansible.builtin.shell:
      loop:
        - "curl -s curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
        - "curl -s curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash" 

    - name: Install RabbitMQ
      ansible.builtin.yum:
        - name: rabbitmq-server 
          state: installed
    
    - name: restart rabbitmq
      ansible.builtin.service:
        name: rabbitmq
        state: restarted 
        enabled: true